import type { UserType } from './UserType';
import type { ReviewType } from './ReviewType';
import type { ProductType } from './ProductType';

export type RootStackParamList = {
  Search: undefined;
  Filter: undefined;
  Register: undefined;
  Checkout: {
    total: string;
    subtotal: string;
    discount: number;
    delivery: number;
    walletDiscount: any;
    promocode: any
  };
  Menulist: { category: string };
  MyAddress: undefined;
  Onboarding: undefined;
  EditProfile: undefined;
  OrderFailed: undefined;
  AddANewCard: undefined;
  MyVehicles: undefined;
  ProfileScreen: undefined;
  OrderHistory: undefined;
  TaskList: undefined;
  LeaveAReview: undefined;
  MyPromocodes: undefined;
  TabNavigator: undefined;
  SplashScreen: undefined;
  TabEnNavigator: undefined;
  Notifications: undefined;
  LeaveAReviews: undefined;
  PaymentMethod: undefined;
  ForgotPassword: undefined;
  TrackYourOrder: undefined;
  AddANewAddress: undefined;
  Product: { item: ProductType };
  OrderSuccessful: undefined;
  Promocodes: undefined;
  NewPassword: undefined;
  ConfirmationCode: undefined;
  MyPromocodesEmpty: undefined;
  SignUpaccountCreated: undefined;
  VerifyYourPhoneNumber: undefined;
  Wallet: undefined;
  Reviews: undefined;
  ShippingDetails: undefined;
  Description: { description: string };
  ForgotPasswordSentEmail: undefined;
  Created: undefined;
  Forgot: undefined;
  SignIn: undefined;
  SignUp: undefined;
  VerifyEmail: { email: string };
  ResetPassword: { email: string };
  EmailConfirm: { email: string };
  ResetPasswordSuccess: undefined;
};
